GRID_WIDTH = 10
GRID_HEIGHT = 10
OBSTACLE_DENSITY = 0.15

NUM_PACKAGES = 5
NUM_ROBOTS = 2
RANDOM_SEED = 42
MAX_TIMESTEPS = 500

ROBOT_START_POSITIONS = None

PACKAGE_LOCATIONS = None

OBSTACLE_LOCATIONS = None

TEXT_UPDATE_DELAY = 0.5
TEXT_USE_COLORS = True
TEXT_SHOW_PATHS = True

PYGAME_WINDOW_SIZE = 700
PYGAME_FPS = 2

PATHFINDING_HEURISTIC = 'manhattan'

CONFLICT_WAIT_DURATION = 1

SHOW_STATISTICS = True
VERBOSE_OUTPUT = True


def config_small_test():
    global GRID_WIDTH, GRID_HEIGHT, NUM_PACKAGES, NUM_ROBOTS, OBSTACLE_DENSITY
    GRID_WIDTH = 5
    GRID_HEIGHT = 5
    NUM_PACKAGES = 2
    NUM_ROBOTS = 2
    OBSTACLE_DENSITY = 0.1


def config_medium():
    global GRID_WIDTH, GRID_HEIGHT, NUM_PACKAGES, NUM_ROBOTS, OBSTACLE_DENSITY
    GRID_WIDTH = 10
    GRID_HEIGHT = 10
    NUM_PACKAGES = 5
    NUM_ROBOTS = 2
    OBSTACLE_DENSITY = 0.15


def config_large():
    global GRID_WIDTH, GRID_HEIGHT, NUM_PACKAGES, NUM_ROBOTS, OBSTACLE_DENSITY
    GRID_WIDTH = 20
    GRID_HEIGHT = 20
    NUM_PACKAGES = 10
    NUM_ROBOTS = 3
    OBSTACLE_DENSITY = 0.2


def config_stress():
    global GRID_WIDTH, GRID_HEIGHT, NUM_PACKAGES, NUM_ROBOTS, OBSTACLE_DENSITY
    GRID_WIDTH = 30
    GRID_HEIGHT = 30
    NUM_PACKAGES = 15
    NUM_ROBOTS = 3
    OBSTACLE_DENSITY = 0.25


def config_predefined_test():
    global GRID_WIDTH, GRID_HEIGHT, NUM_PACKAGES, NUM_ROBOTS
    global ROBOT_START_POSITIONS, PACKAGE_LOCATIONS, OBSTACLE_LOCATIONS
    
    GRID_WIDTH = 8
    GRID_HEIGHT = 8
    NUM_PACKAGES = 3
    NUM_ROBOTS = 2
    
    ROBOT_START_POSITIONS = [(0, 0), (7, 7)]
    PACKAGE_LOCATIONS = [(3, 3), (5, 2), (2, 6)]
    OBSTACLE_LOCATIONS = [(3, 4), (4, 4), (5, 4), (3, 5), (5, 5)]
